### ISSUE TITLE
'Are you sure' dialogen

### ISSUE THREAD

**Issue by robstek** [IDgis/geoide-composer#107]
Waarschuwing bij verwijderen item

**Comment by robstek** [comment]
eerst uitzoekwerk voor dit standaard patroon [1 uur]

**Comment by robstek** [comment]
http://ethaizone.github.io/Bootstrap-Confirmation/# ??

https://github.com/aldeed/meteor-delete-button ??

https://atmospherejs.com/matdutour/popup-confirm !!!!

**Comment by NijzinkM** [comment]
Er wordt om bevestiging gevraagd bij het verwijderen van services, lagen en kaarten.
