### ISSUE TITLE
Tooltips invoer schermen

### ISSUE THREAD

**Issue by robstek** [IDgis/geoide-composer#108]
uitzoeken hoe tooltips in autoform te zetten
uitzoeken hoe tooltips in jstree te zetten

**Comment by HermanAssink** [comment]
Wat is het resultaat van dit onderzoek en waarom zie ik ze nog niet in de invoerschermen?

**Comment by robstek** [comment]
er zijn copy paste fouten waardoor i18n van maps bij layers wordt gebruikt etc
