### ISSUE TITLE
mongo db backup/replication

### ISSUE THREAD

**Issue by robstek** [IDgis/geoide-composer#112]
Op de windows server een backup / replicatie taak aanmaken

**Comment by robstek** [comment]
uitzoek werk: hoe dit voor mongo te regelen

**Comment by robstek** [comment]
zie geoide-admin-deployment/9

**Comment by robstek** [comment]
in C:\MongoDB staat een backup script dat in de Windows Task Scheduler wordt gebruikt (nightly backup @ 01:00 uur).
Verwijst eerst naar C:\tmp, als backuppen  goed gaat naar C:\MongoDB\dump\scheduled\

**Comment by HermanAssink** [comment]
Backup is een verantwoordelijkheid van de systeembeheer bij de klant. Wij moeten een script en/of instructie aanleveren. Graag deze instructie toevoegen aan de installatie-instructie van Meteor.JS
