### ISSUE TITLE
Sorteren op naam

### ISSUE THREAD

**Issue by NijzinkM** [IDgis/geoide-composer#117]
De elementen in de lijsten (bij services, lagen en kaarten) worden gesorteerd op moment van toevoegen. Als er veel elementen in een lijst staan is het handig als deze op naam worden gesorteerd.

**Comment by NijzinkM** [comment]
Alle lijsten worden gesorteerd op naam. De lijst met lagen bij het configureren van een kaart is ook gesorteerd op naam, maar geeft alleen de labels weer. Hierdoor is de lijst niet alfabetisch geordend. Moet dit op label gesorteerd worden, of op naam (zoals nu)?

**Comment by HermanAssink** [comment]
Moet gesorteerd worden op het zichtbare veld.

**Comment by HermanAssink** [comment]
Lijst "Service laagnaam" bij Lagen is nog niet alfabetisch gesorteerd. Rob, loop je alle lijsten even na?

**Comment by kad-velsl** [comment]
Sortering niet case sensitive maken

**Comment by kad-velsl** [comment]
probleem ziet in MongoDB
zie http://stackoverflow.com/questions/12205546/meteor-sort-case-insensitive
Op het internet vind je allerlei workarounds, maar die zijn niet fraai.
