### ISSUE TITLE
Knop 'hernoem laag' ontbreekt

### ISSUE THREAD

**Issue by NijzinkM** [IDgis/geoide-composer#118]
Bij het configureren van een kaart is de knop 'hernoem groep' wel beschikbaar, maar 'hernoem laag' niet.

**Comment by robstek** [comment]
een laag mag niet hernoemd worden omdat de naam een uniek veld is (zoals een primary key) in de database.

**Comment by HermanAssink** [comment]
Bij het toevoegen van een laag kun je deze een andere naam in de laagstructuur v.d. kaart geven. Dit betreft toch het label dat je vrij mag wijzigen?

**Comment by robstek** [comment]
Het is nu de laagnaam die in de select wordt getoond, dit zou het label kunnen worden.
Het label kan zonder probleem gewijzigd worden.

**Comment by robstek** [comment]
Het label wordt niet gewijzigd bij de laag zelf en dus niet meegenomen in de maps.json configuratie voor  de viewer.
Het is dus puur cosmetisch voor het formulier kaart opmaken en niet voor de buitenwereld.
