### ISSUE TITLE
FeatureType naam wordt niet ververst

### ISSUE THREAD

**Issue by NijzinkM** [IDgis/geoide-composer#119]
Bij het configureren van een laag wordt de lijst onder 'FeatureType naam' niet ververst. Reproduceren:
- Kies bij Servicelagen > Service: PDOK Bestuurlijke grenzen
- Kies bij Servicelagen > Service laagnaam: gemeenten
- Kies bij Feature type > Service: Bestuurlijke grenzen (WFS)
- De lijst 'Featuretype naam' blijft leeg
- Kies bij Feature type > Service: CRS Limburg WFS
- De lijst 'Featuretype naam' geeft acht mogelijkheden
- Kies weer bij Feature type> Service: Bestuurlijke grenzen (WFS)
- De lijst 'Featuretype naam' blijft nu hetzelfde weergeven

**Comment by robstek** [comment]
De bestuurlijk grenzen WFS  wordt waarschijnlijk niet goed geparsed voor die specifieke versie. Zie ook #123

**Comment by NijzinkM** [comment]
Lijst wordt ververst
