### ISSUE TITLE
Label bij servicelaag en FeatureType

### ISSUE THREAD

**Issue by NijzinkM** [IDgis/geoide-composer#120]
Betreffende het configureren van een laag:
Is het nodig om de gebruiker een label te laten geven aan servicelaag en FeatureType?

**Comment by robstek** [comment]
label weglaten als viewer niets mee doet. 
viewer json heeft het nodig??

**Comment by robstek** [comment]
Default invullen met gekozen laagnaam of featuretype

zie ook #149

**Comment by kad-velsl** [comment]
service layer label wordt getoond in TOC, dit is soms niet wenselijk als het plaatjes zelf al een label bevat. Daarom optioneel maken.

**Comment by kad-velsl** [comment]
servicelayer label is nu optioneel

**Comment by HermanAssink** [comment]
Leeg laten geeft bij laag Cultuurhistorie Limburg een fout bij refresh.

**Comment by robstek** [comment]
[x] xcxv
[] xcvxcvx

**Comment by robstek** [comment]
Testen of dit te reproduceren is ??
