### ISSUE TITLE
Witruimte onder knoppen

### ISSUE THREAD

**Issue by NijzinkM** [IDgis/geoide-composer#121]
Er mist een lege ruimte onder de knoppen onderaan de pagina, bijvoorbeeld in de lijst met services, de lijst met lagen of bij het configureren van een laag.

**Comment by robstek** [comment]
witruimte toevoegen bij alle formulieren (lijsten en wijzig formulieren) [1 uur]

**Comment by NijzinkM** [comment]
Witruimte is op elke pagina en in elk vensterformaat aanwezig
