### ISSUE TITLE
Knop voor nieuw element niet zichtbaar

### ISSUE THREAD

**Issue by NijzinkM** [IDgis/geoide-composer#122]
Als de lijst met services, lagen of kaarten langer is dan de pagina kan weergeven, is de knop om een element toe te voegen niet zichtbaar. De knop staat namelijk onderaan de lijst en is hierdoor lastiger te vinden dan wanneer deze meteen in het zicht staat.

**Comment by robstek** [comment]
Voorstel:
- Knop naar boven op dezelfde hoogte als de kop (bv 'Services')  en boven de edit/delete knoppen [1 uur]
- paginering van lijsten zodat geen scrollbar nodig is [5 uur]

**Comment by NijzinkM** [comment]
Knop staat nu op een logische zichtbare plaats
