### ISSUE TITLE
Lijst met versies

### ISSUE THREAD

**Issue by NijzinkM** [IDgis/geoide-composer#123]
Bij het configureren van een service is het mogelijk om de WMS-. WFS- of TMS-versie te kiezen. Wordt de versie gebruikt die je hier kunt selecteren of wordt de versie uit de GetCapabilities-request gehaald? Is het dus ook mogelijk een versie te selecteren die niet ondersteund wordt?

**Comment by robstek** [comment]
De getoonde versie komt uit een vaste lijst ipv de GetCapabilities.

**Comment by HermanAssink** [comment]
Rob, graag een schatting aan deze issue toekennen voor het uit de capabilities halen v.d. de ondersteunde vesie

**Comment by robstek** [comment]
aantal GetCap requests uitgeprobeerd:
WFS geeft lijst met versies

```
<ows:ServiceTypeVersion>2.0.0</ows:ServiceTypeVersion>
<ows:ServiceTypeVersion>1.1.0</ows:ServiceTypeVersion>
```

maar ook:

```
<ows:Parameter name="version">
<ows:AllowedValues>
<ows:Value>2.0.0</ows:Value>
<ows:Value>1.1.0</ows:Value>
</ows:AllowedValues>
</ows:Parameter>
```

WMS niet, laatste versie als  attribuut in WMS_Capabilities tag
`version="1.3.0"`

**Comment by HermanAssink** [comment]
Rob, klopt, WMS laat niet de beschikbare versies in de WMS zien. Hoeveel werk is het om per type service een handige default in te stellen (WMS=1.1.1, WFS=1.1.0 en TMS=1.0.0)?

**Comment by robstek** [comment]
default: 1 uur om uit te zoeken wat de beste wijze is
rest tijd:
1 uur om versie uit de getcap te halen (alleen WFS)
3 uur om de getcap/getft parsing voor alle mogelijke WMS/WFS versies uit te breiden

**Comment by robstek** [comment]
Afgesproken: alleen defaults toevoegen, niet de versies uit GetCap lezen

**Comment by HermanAssink** [comment]
Keuzelijst voor versie is gewijzigd in radiobutton, maar er wordt geen default geselecteerd

**Comment by NijzinkM** [comment]
Er wordt per type service een standaardwaarde geselecteerd.
