### ISSUE TITLE
fileUpload geeft fout

### ISSUE THREAD

**Issue by kad-velsl** [IDgis/geoide-composer#136]

**Comment by kad-velsl** [comment]
![geoide-admin-fout](https://cloud.githubusercontent.com/assets/9080474/17665974/3ad5d418-62fe-11e6-8c5a-06ee17367ab1.png)

**Comment by kad-velsl** [comment]
In de log file:
no such file or directory, open 'C:\geoide-admin\deployment\test.meteor\local\build\programs\server\undefined\public.uploads\tmp\80604d5bcd218c4d29191f3b859f5156'

**Comment by NijzinkM** [comment]
Bestanden uploaden werkt. Afbeeldingen worden goed weergegeven (JPEG, PNG, GIF, BMP). Als een bestand niet kan worden weergegeven, bijvoorbeeld een tekstbestand, wordt er het volgende getoond:
![legendgraphic](https://cloud.githubusercontent.com/assets/6792039/17739352/1f0a893e-6495-11e6-9f31-a26b09b16c55.png)

Zie #164
