### ISSUE TITLE
Welke tekens toegestaan in namen van services, lagen en kaarten?

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoide-composer#147]
Nu lijken alle tekens toegestaan, maar is dat terecht? Mogen bijv !@#$%^&*()_+?

**Comment by robstek** [comment]
Alles kan op dit moment.

Hier moet nog een regexp komen te staan.
Bijv a-z,A-Z,0-9,- en geen spaties

**Comment by NijzinkM** [comment]
Bij het configureren van een service, laag of kaart is het niet mogelijk om bij de naam de tekens !@#$%^&*()+? in te voeren. Er komt dan te staan: Naam geen geldige reguliere expressie.
