### ISSUE TITLE
Legend Graphic kan niet worden leeggemaakt

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoide-composer#148]
Als eenmaal een legend graphic is ge-upload kan die niet meer worden verwijderd.

**Comment by robstek** [comment]
Er kan een 'leegmaak' knop worden toegevoegd. 
Deze wist de url en zet een leeg plaatje neer.

**Comment by NijzinkM** [comment]
Legenda-afbeelding kan worden verwijderd met een knop.
