### ISSUE TITLE
naam Legend Graphic bestand bewaren?

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoide-composer#151]
Het lijkt me handig om de naam v.d. LG, in geval van eigen plaatjes, in de DB te bewaren, zodat we bij het downloaden v.d. LG's naar file betekenisvolle namen kunnen gebruiken.

**Comment by robstek** [comment]
Hier wordt in voorzien. De binare content van het  wordt naast de oorspronkelijke naam en het mime type bewaard.

Op dit moment is de naam van het plaatje  'unique'.
Zou dit een bezwaar zijn?

**Comment by robstek** [comment]
Naam image staat in de url die in de viewer servicelayers.json staat
