### ISSUE TITLE
Kan geen zoekveld selecteren bij zoekingang, bijv. bij laag percelen

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoide-composer#152]

**Comment by robstek** [comment]
misschien gaat hier nog iets mis bij het parsen van DescribeFeatureTypes.

**Comment by robstek** [comment]
kon niet worden gereproduceerd:
bij welke laag, service laag, featuretype, featuretype naam?

**Comment by HermanAssink** [comment]
Laag percelen (op testserver, zoals vermeld in titel)

**Comment by robstek** [comment]
Niet gereproduceerd:
laag 'percelen' bij crs-deegree-wfs-sll:
bij andere selecteren FT naam , veranderd de lijst met Zoekveld en hierin kan een zoekveld worden gekozen en opgeslagen.
