### ISSUE TITLE
Kan geen zoekingang maken bij AAN-WFS

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoide-composer#154]
Selecteren van een zoekveld is geblokkeerd en na verwijderen v.d. zoekingang werkt de +-knop niet meer.

**Comment by robstek** [comment]
Zoekingangen zijn disabled als het servicelaag type 'default' is.

Ze moeten dan ook onzichtbaar zijn om verwarring te voorkomen.

**Comment by robstek** [comment]
wat hier speelt is dat er slechts 1 featuretype in de AAN-WFS zit. 
Alleen bij iets anders kiezen in de lijst featuretypes worden de zoekingangen gevuld.

**Comment by HermanAssink** [comment]
Is dus een bug.

**Comment by robstek** [comment]
zie #163 voor lijsten met 1 item
dit issue lost op dat bij laagtype default de zoekingangen niet zichtbaar zijn in formulier
