### ISSUE TITLE
LegendGraphic plaatje bij bestanden die niet kunnen worden weergegeven

### ISSUE THREAD

**Issue by NijzinkM** [IDgis/geoide-composer#164]
Als een bestand niet kan worden weergegeven, bijvoorbeeld omdat het geen afbeelding is, wordt het volgende getoond:
![legendgraphic](https://cloud.githubusercontent.com/assets/6792039/17739471/7e827796-6495-11e6-8f53-35993f45c080.png)

Misschien is het duidelijker om hier een tekst te plaatsen die duidelijk maakt dat het bestand niet kan worden weergegeven en/of dat het niet als legenda kan worden gebruikt.

**Comment by robstek** [comment]
tekst 'Niet gevonden' als er geen legend graphic wordt geladen
