### ISSUE TITLE
Map form: laag toevoegen negeert 'zichtbaar' select

### ISSUE THREAD

**Issue by robstek** [IDgis/geoide-composer#171]
Als de laag onderaan de kaart voor het eerst is toegevoegd wordt het zichtbaarheids vinkje niet meegenomen in de database.
Daarna, bij editen van de kaart wordt de toestand van de checkbox wel steeds  in de db gezet.

**Comment by kad-velsl** [comment]
Probleem onderzocht, lijkt een bug in de checkbox plugin van jstree. Voorlopig beschouwen we dit als een known issue

**Comment by robstek** [comment]
is opgelost, was de state plugin
