### ISSUE TITLE
namespace awareness voor Featuretypes

### ISSUE THREAD

**Issue by kad-velsl** [IDgis/geoide-composer#173]

**Comment by robstek** [comment]
Parsen van xml gebeurd met package peerlibrary:xml2js .

Hier moet optie 'xmlns=true' worden gebruikt.
Dit levert namespace onafhankelijke javascript objecten op .

Code aanpassing nodig in /geoide-admin/imports/startup/server/parse_capabilities.js in alle methodes die gebruilk maken van "getXml : function (host, params){...}".
