### ISSUE TITLE
wijzigen label in laagtree werkt niet door in viewer

### ISSUE THREAD

**Issue by kad-velsl** [IDgis/geoide-composer#177]

**Comment by kad-velsl** [comment]
De label van een laag uit de tree overschrijft niet het label van een laag in de viewer. Er zijn 2 opties: label van laag niet wijzigbaar maken in de geoide Composer of label van laag binnen kaart config overschrijft label van laag in viuewer

**Comment by HermanAssink** [comment]
Label in layertree niet wijzigbaar maken

**Comment by HermanAssink** [comment]
Oké
