### ISSUE TITLE
Tooltip bij laagtype (radiobutton) wordt niet getoond

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoide-composer#178]

**Comment by kad-velsl** [comment]
De tooltips verschijnen op het moment dat je over het form input element hovert, dus als je op een radiobutton zelf gaat staan.

**Comment by kad-velsl** [comment]
Toevoegen in de helptekst

**Comment by kad-velsl** [comment]
Regel over tooltip toegevoegd bij lagen, kaarten en services
