### ISSUE TITLE
Een laag mag maar 1 keer voorkomen in een kaart

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoide-composer#182]
Dezelfde laag twee keer in een kaart opnemen heeft geen zin. Bovendien geeft het waarschijnlijk problemen in de viewerprogrammatuur.

**Comment by kad-velsl** [comment]
Suggestie: Als laag al in kaart voorkomt verwijderen uit laag keuzelijst zodat deze niet meer kan worden toegevoegd

**Comment by kad-velsl** [comment]
Doen

**Comment by HermanAssink** [comment]
Werkt, laag kan maar 1 keer worden gekozen. Als laag uit kaart wordt verwijderd wordt deze weer toegevoegd aan de keuzelijst
