### ISSUE TITLE
check op url fails for localhost adresses

### ISSUE THREAD

**Issue by kad-velsl** [IDgis/geoide-composer#185]

**Comment by kad-velsl** [comment]
In het service formulier wordt d input van een url gecheked mbv
SimpleSchema.RegEx.Url
Deze check staat deze urls niet toe:
localhost:8080
127.0.0.1:8080
oudeijssel:8080

wel bijvoorbeeld:
oudeijssel.com:8080 of
123.0.0.1:8080 of
148.251.183.26 

Dit is een probleem als de crs2 services op dezelfde service als de viewer draaien. Misschien moeten we een eigen RegEx implementeren.

**Comment by kad-velsl** [comment]
Bij CA/CRS klanten wordt naar de deegree service verwezen mbv een hostnaam en poort

**Comment by kad-velsl** [comment]
Andere regex controle gemaakt checkt in elk geval op protocol en eventueel op poort

**Comment by HermanAssink** [comment]
Graag een knopje op het formulier toevoegen waarmee men de capabilities bij de ingevoerde url kan ophalen om zo de url testen.

**Comment by kad-velsl** [comment]
button toegevoegd die de capabilities opvraagt en opent in een nieuw scherm

**Comment by HermanAssink** [comment]
Werkt, handig die knop Controleren
