### ISSUE TITLE
PDOK wms laag landelijkfietsroutes geeft geen legendaplaatje

### ISSUE THREAD

**Issue by kad-velsl** [IDgis/geoide-composer#186]

**Comment by kad-velsl** [comment]
In de parsing voor de legendGraphic  wordt een eigen url gebouwd op basis van wat er in de capabilities als GetLegendGraphic request wordt geadverteerd. Dit hoeft er echter niet te zijn (zoals in de PDOK service). Beter is het om te werken met de url die wordt geadverteerd in de Layer onder Style.

**Comment by kad-velsl** [comment]
Gaan we doen

**Comment by HermanAssink** [comment]
Werkt.
