### ISSUE TITLE
Lagen in kaart worden uitgevinkt

### ISSUE THREAD

**Issue by NijzinkM** [IDgis/geoide-composer#187]
Als een kaart A wordt opgeslagen en direct daarna weer wordt bewerkt, is de configuratie van de zichtbaarheid van de lagen correct opgeslagen (de juiste vakjes zijn aangevinkt). Als vervolgens kaart B wordt bewerkt en men daarna weer teruggaat naar het bewerken van kaart A, dan is geen enkel vakje meer aangevinkt en moet de zichtbaarheid van de lagen opnieuw worden ingesteld.

**Comment by NijzinkM** [comment]
Misschien gerelateerd aan #171

**Comment by kad-velsl** [comment]
uitzoeken

**Comment by HermanAssink** [comment]
Is dit uitgezocht? Wat was de uitkomst?

**Comment by robstek** [comment]
Scenario is nagespeeld en probleem niet gereproduceerd.

**Comment by HermanAssink** [comment]
Niet gereproduceerd
