### ISSUE TITLE
Tekstuele aanpassingen nav test met Evert Jan

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoide-composer#188]
- vieer -> viewer
- vandaan -> op
- uitleg in HELP bij knop Controleren
- HELP mbt "initieel zichtbaar" kan weg
- Engelse tekst zoals "Legend Graphic" omzetten naar NL
- lijst in HELP van verplichte waarden obv venster GIS-koppelingen in CRS

**Comment by robstek** [comment]
laatste regel wordt opgelost in #200
