### ISSUE TITLE
Veld Initiële query onzichtbaar maken bij default lagen

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoide-composer#190]

**Comment by kad-velsl** [comment]
Zie volgende commentaar in de code:

/*
        \* 'disabled' works reactive i.e. after the form is rendered
        \* whereas optional, omit, hidden do not 
        */

Het hidden maken werkt dus niet reactive, lijkt me niet zo'n goede optie.

Wellicht is het mogelijk om via de stijl de disabled elementen onzichtbaar te maken

**Comment by kad-velsl** [comment]
Het is mogelijk om het query veld onzichtbaar te maken, de Properties box en het label blijven zichtbaar, ik weet niet of het hierdoor duidelijker wordt.

**Comment by HermanAssink** [comment]
Wel beter zo.
