### ISSUE TITLE
Fout bij viewer-refresh na update in Composer melden aan Composer gebruiker

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoide-composer#195]

**Comment by robstek** [comment]
Toegevoegd:  alert bij http error
Nog te doen:
- check viewer response en geef alert indien NOK
  - alert wanneer http code <>200, inhoudelijk is de viewer response leeg

**Comment by HermanAssink** [comment]
Hoe kan ik dit testen, m.a.w. hoe kan ik een fout introduceren?

**Comment by robstek** [comment]
Te testen:

in C:\geoide-admin\development\settings.json 
in het item
`"reloadConfigUrl": "http://....."`
TIJDELIJK  een niet werkende url (die bijv een IIS http 500 geeft) te zetten.

Een reproduceerbare error response van de viewer triggeren is niet zomaar mogelijk.
Dit kan alleen lokaal tijdens development door in de composer code de output van de json voor de viewer aan te passen.

**Comment by HermanAssink** [comment]
Netjes
