### ISSUE TITLE
te technische foutmelding naam laag

### ISSUE THREAD

**Issue by kad-velsl** [IDgis/geoide-composer#196]

**Comment by kad-velsl** [comment]
![fout](https://cloud.githubusercontent.com/assets/9080474/18353903/0b7bfffa-75e4-11e6-8323-4106b1995d5a.png)

**Comment by robstek** [comment]
voor namen van service, laag en map de melding aangepast. 
voor service endpoint de regexp aangepast en melding toegevoegd
