### ISSUE TITLE
Usability Laag configuratie: Service laagnaam wordt niet gewist als andere service wordt gekozen

### ISSUE THREAD

**Issue by robstek** [IDgis/geoide-composer#206]
Als in scherm 'Laag configuratie' bij 'Servicelagen' een andere service of de optie '(Selecteer)' wordt gekozen wordt een al bestaande lijst in 'Service laagnaam'  niet eerst gewist.

**Comment by HermanAssink** [comment]
Huidige oplossing niet snel genoeg.

**Comment by robstek** [comment]
opgelost met cache zie #218
