### ISSUE TITLE
Usability Laag configuratie: Featuretype naam wordt niet gewist als andere service wordt gekozen

### ISSUE THREAD

**Issue by robstek** [IDgis/geoide-composer#207]
Als in scherm 'Laag configuratie' bij 'Featuretypen' een andere service of de optie '(Selecteer)' daarin wordt gekozen, wordt een al bestaande lijst in 'Featuretype naam'  niet eerst gewist.

**Comment by HermanAssink** [comment]
Huidige oplossing niet snel genoeg

**Comment by robstek** [comment]
opgelost met cache zie #218
