### ISSUE TITLE
Usability Kaart configuratie: knop 'Laag toevoegen' voegt lege laag toe als lijst 'Kies een laag' leeg is

### ISSUE THREAD

**Issue by robstek** [IDgis/geoide-composer#209]

**Comment by HermanAssink** [comment]
Kan de knop "Laag toevoegen" worden uitgegrijsd als de lijst leeg is?

**Comment by robstek** [comment]
Dat moet inderdaad niet al te moeilijk zijn

**Comment by robstek** [comment]
Alle knoppen worden gedisabled als dat nodig is.
Voorbeeld : als een laag wordt geselecteerd , wordt de knop 'hernoem groep' disabled.
