### ISSUE TITLE
Add control printFormat

### ISSUE THREAD

**Issue by robstek** [IDgis/geoide-composer#211]
Toevoegen bij Service configuratie

**Comment by robstek** [comment]
Zie issue #231 van geoide-commons

**Comment by robstek** [comment]
in services.json toevoegen:

`printFormat: "image/jpg",`

**Comment by HermanAssink** [comment]
Keuzelijst voor format wordt blijkbaar niet gevuld met door WMS ondersteunde formaten

**Comment by robstek** [comment]
werkt wel, maar waarschijnlijk vertraagd door autoform reactivity
opgelost met cache zie #218
