### ISSUE TITLE
Snelheid bij opvragen externe services (WMS/WFS) te laag

### ISSUE THREAD

**Issue by robstek** [IDgis/geoide-composer#218]
Door Autoform GetFieldValue wordt vaak (soms 8x) dezelfde service request uitgevoerd. dit leidt tot zichtbare vertraging bij vullen keuzelijsten (zie service Print Formaat).

zie ook #206, #207

**Comment by robstek** [comment]
Alle WMS/WFS request resultaten worden opgeslagen in een Map met als key de parameters van de desbetreffende methode. 
Doordat Javascript (Node.js) in essentie single threaded is, treedt hier geen race conditie op omdat Map niet kan worden benaderd vanuit  meerdere methoden/threads.

De user interface wordt hiermee merkbaar sneller voor de gebruiker.

**Comment by HermanAssink** [comment]
Prima! Capabilities  van GeoPublisher zijn in ca 5 seconden geladen
