### ISSUE TITLE
LegendGraphic van GeoPublisher wordt niet geladen

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoide-composer#222]
Zie service GeoPublisher_acc_overall, bijvoorbeeld bij layer Aardkundige waarden.
LegendGraphics url is wel correct:
http://acc-services.geodataoverijssel.nl/geoserver/wms?request=GetLegendGraphic&format=image/png&width=20&height=20&layer=B4_Aardkundige_waarden

Misschien agv url-encoding?

**Comment by robstek** [comment]
geen url-encoding probleem maar fout in programmatuur

**Comment by HermanAssink** [comment]
Wordt nu inderdaad geladen, maar lijkt niet gecacht te worden. Laad traag, ook bij herhaald oproepen.

**Comment by HermanAssink** [comment]
Wordt nu wel gecacht, maar initieel niet zichtbaar, zie AW, Aardkundige waarden

**Comment by robstek** [comment]
is (nog) niet gereproduceerd.

Als een laagformulier wordt geopend, is aan het legendaplaatje de url gekoppeld die het laatst is opgeslagen.
Het tonen van het plaatje is dan een actie van de browser en niet van geoide composer.

Ook als in Chrome network throttling wordt aangezet, verschijnt het plaatje van AW snel in beeld.

**Comment by robstek** [comment]
Het probleem is te zien in FireFox!!! speelt bij mij niet in chrome.

Daar wordt het plaatje pas getoond, als bijv. in de service laagnaam lijst wordt geklikt.

**Comment by robstek** [comment]
in FF is er na keuze in laag select box een foutmelding ni de console te zien:
`TypeError: srcSelect[0] is undefined`

is opgelost: verschillen tussen chrome, FF en IE

**Comment by robstek** [comment]
Het opbouwen van de select box met opties van m.n. GeoPublisher duurt zeer lang in IE Edge. 
Het gaat hier om > 600 lagen cq select options.

**Comment by HermanAssink** [comment]
Omdat dit de overall service van GeoPublisher betreft is dit geen probleem. Deze service is niet bedoeld om te gebruiken. Andere services van Overijssel moeten wel vlot laden, bijv:
http://services.geodataoverijssel.nl/geoserver/Natuurbeheerplannen/wms?
en
http://services.geodataoverijssel.nl/geoserver/B22_wegen/wms?

**Comment by robstek** [comment]
IE Edge: bij natuurbeheerplannen opent de selectielijst in ca 1 sec, b22-wegen (ca 35 lagen) in 2 sec
De gehele GeoPub duurt ongeveer 30 sec (!), bij chrome, ff 1 a 2 sec.

Als afgerond beschouwen?
