### ISSUE TITLE
versie uit settings.json

### ISSUE THREAD

**Issue by robstek** [IDgis/geoide-composer#227]
haal de versie uit settings.json en zet deze hardcoded in main.html

**Comment by robstek** [comment]
Als er wel een version in settings.json wordt gezet, overruled deze de hardcoded versie in html. 
Dit is echter niet meer beschreven in de README..

**Comment by HermanAssink** [comment]
Deze redundantie leidt m.i. tot verwarring. Wat mij betreft alleen versie in de HTML

**Comment by HermanAssink** [comment]
Staat nu alleen in HTML
