### ISSUE TITLE
WMS Archeologie ODRU werkt niet

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoide-composer#234]
Deze wms http://odru.gispubliek.nl/deegree-webservices/services/wms_archeologie?request=GetCapabilities&service=WMS functioneert niet.
Dit betreft een WMS met groepslagen die ook als groep te tekenen zijn (hebben Name element).
Graag boomstructuur laten zien, indien mogelijk, in keuzelijst met layers.
Zie map demo tbv ODRU

**Comment by robstek** [comment]
In de composer gaat de getWmslayers functie niet diep genoeg voor ODRU lagen, waardoor de onderste nivo's niet gevonden worden.
Er zal in de keuzelijst mbv inspringen van laagtitels duidelijk gemaakt worden wat de boomstructuur  is.:

```
  bkk
  __ Toepassingskaart bovengrond
  __ Bodemfunctieklassenkaart
```

Het op alfabet sorteren van de gehele lijst wordt uitgezet.

**Comment by robstek** [comment]
als een laag geen eigen getlegend url heeft dan wordt deze uit de algemene tag gehaald:

```
 <Capability>
    <Request>
        <GetCapabilities>
          <GetMap>
          <GetFeatureInfo>
          <GetLegendGraphic>
```

dit werkt niet altijd, maar wel bijv bij GeoPublisher:
`NBP2016 Ambitiekaart`
