### ISSUE TITLE
WMS luchtfoto ODRU werkt niet

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoide-composer#235]
Betreft ECW-luchtfotos-ODRU-WMS / http://odru.ecw-hosting.nl/lufo/services? in kaart demo tbv ODRU.
Er wordt ook geen LegendGraphic getoond

**Comment by robstek** [comment]
Er is een maxWidth en maxHeight geconfigureerd. Daardoor is een laag niet zichtbaar op 'grote' schermen.
Verder is de getLegenGraphicUrl niet per laag  in de capabilities aanwezig.
 In dat geval moet de composer de url uit

```
<Capability>
  <Request>
    <GetLegendGraphic>
```

halen.

**Comment by HermanAssink** [comment]
OGC Service exceptions zichtbaar maken in de viewer zodat we in de toekomst tijdverspilling voorkomen

**Comment by robstek** [comment]
wordt opgelost in https://github.com/IDgis/geoide-commons/issues/271
