### ISSUE TITLE
Kan Naam en Label van layer default worden gevuld met de naam van eerstgekozen servicelayer?

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoide-composer#245]
Vaak wil je de naam (bijna) gelijk aan die van de serviceLayer, scheelt typewerk.

**Comment by robstek** [comment]
Dit werkt wel, maar:

1a. wat je ziet in lijst met servicelayers zijn de labels (WMS _Title_)
1b. wat je krijgt in Name of Label van de layer is de WMS _Name_
- deze kan tekens bevatten die niet zijn toegestaan in layer Name
- er kunnen niet zinvolle namen zijn: ArcGis bijvoorbeeld bevat als naam cijfers: 14, 15, ..,  

2a. als in de LayerSchema code om de waarde van een veld te veranderen, de actuele waarde van datzelfde veld wordt opgevraagd (reactive met autoform) ontstaat er een loop. 
2b. Zichtbaar oa door console.log regels die niet ophouden tot een verhoogde CPU belasting zolang het form openstaat.
