### ISSUE TITLE
Vraag: Moet er nog iets worden gedaan om toekomstige DB upgrades te vereenvoudigen?

### ISSUE THREAD

**Issue by HermanAssink** [IDgis/geoide-composer#246]

**Comment by robstek** [comment]
meteor package [https://atmospherejs.com/percolate/migrations](https://atmospherejs.com/percolate/migrations)

Voor elke schema verandering in de tijd een migrate up en/of down toevoegen:   

```
Migrations.add({
  version: 1,
  up: function() {//code to migrate up to version 1} 
  down: function() {//code to migrate down to version 0} 
});
```

Aanroep vanuit applicatie of meteor shell:  
`Migrations.migrateTo('latest');`

**Comment by robstek** [comment]
Dit kunnen we t.z.t. toevoegen aan de code als we aan een volgende aanpassing van de collectie schema's toe zijn.

**Comment by HermanAssink** [comment]
Migrations update alle bestaande collecties. Oude versies van het schema blijven bewaard. Soms kan worden volstaan met het toevoegen van een  extra kolom. Dan blijft de oude versie niet bewaard.
