### ISSUE TITLE
Laag configuratie: probleem met PDOK AHN TMS

### ISSUE THREAD

**Issue by robstek** [IDgis/geoide-composer#255]
geen laagnamen in select box lijst.  
geconstateerd bij versie 1.0-SNAPSHOT-227

**Comment by robstek** [comment]
- geen AHN TMS bij PDOK gevonden
  - wel WMTS, maar dit wordt door composer niet ondersteund.

Graag de exacte TMS url waarbij het probleem is geconstateerd of hertesten met nieuwste versie.

**Comment by robstek** [comment]
probleem verder geanalyseerd:
- komt voor bij elke TMS
- wel altijd een lijst met daarin een TMS laagnaam 
- maar staat default op Selecteer ipv de opgeslagen laagnaam
  - er werd geen string met laagnaam maar een array aan de lijst toegevoegd
  - array in de lijst matched niet met string in db, daarom stond de selectie in de lijst niet op de opgeslagen laagnaam.

**Comment by HermanAssink** [comment]
Getest met TMS van AAN: werkt
