### ISSUE TITLE
initial_query "geen"

### ISSUE THREAD

**Issue by kad-velsl** [IDgis/geoide-composer#264]
In de mongo db van de default configuratie vind ik bij de gemeenten, luchtfoto en ondergrond laag een initial-query et waarde "geen". In de Viewer wordt hierop gecontroleerd om de speciale lagen te onderscheiden en "geen"is niet null, dus dat gaat fout.

**Comment by kad-velsl** [comment]
Ik heb "geen" weggehaald in de default Composer versie (3040) op de acceptatie server. @robstek Kan jij ervoor zorgen dat er een nieuwe default database in de installatie set komt?

**Comment by robstek** [comment]
Zit in de laatste release geoide-admin-deployment:
https://github.com/IDgis/geoide-admin-deployment/releases/tag/1.0.5
