### ISSUE TITLE
Kaart : groepslagen staan onderin layer.json

### ISSUE THREAD

**Issue by robstek** [IDgis/geoide-composer#86]
lagen en groepen worden niet correct getoond in de viewer:
worden niet getoond of de volgorde is niet correct

vergeleken _geoide-viewer test_ en _geoide-viewer limburg_
mogelijke oorzaken van geoide-admin json waardoor viewer verkeerd kaartbeeld toont:
- punt notatie in pk's
- spaties in pk's
- andere karakters in pk's:
  - `"PDOK luchtfoto.luchtfoto_png/EPSG28992"`
  - `"BRT achtergrondkaart grijs.brtachtergrondkaartgrijs@EPSG%3A28992@png8"`
- _ga_ groepslagen staan onderin in layers.json ipv bij de bijbehorende lagen
  - volgorde belangrijk?
- lege velden staan wel in _ga_ json, niet _gv_ json:

```
     "state": {},
     "properties": {}
```
- volgorde van lagen afdelingen, lijnelem, puntelem, gebouwen is identiek in json maar zijn verschillend in legenda's van beide viewers.

**Comment by kad-velsl** [comment]
De configuratie voor de kaart afdelingen werd gelezen uit de classpath configuratie, terwijl de geoide-admin configuratie een kaart Afdelingen bevatte en geen afdelingen. Door de viewer te starten met de juiste kaartnaam werd wel de gegenereerde configuratie gelezen. Inmiddels is de naam van de kaart in de configuratie aangepast.
